CREATE TABLE notes (
    note_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_title TEXT NOT NULL,
    note_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    note_description TEXT,
    folder_id INTEGER REFERENCES folders(folder_id) ON DELETE CASCADE NOT NULL
);

